Interface implementation
ksenmel/Barcode-Detection pull request #1
Opened 2023-11-10 20:26 UTC by ksenmel

- pyzbar
- onnx-yolov7

2023-11-10 21:27 UTC, vnmsklnk requested changes
Let's also change the structure of the repository. It is better to put all code in a separate folder (you can call it `barcode_detection`)

2023-11-10 21:27 UTC, vnmsklnk commented on boundingbox/.DS_Store
it's unnecessary

2023-11-10 21:27 UTC, vnmsklnk commented on boundingbox/BoundingBox.py
> +    def __init__(self, x, y, width, height):
```suggestion
class BoundingBox:
    def __init__(self, x: int, y: int, width: int, height: int):
```

2023-11-10 21:27 UTC, vnmsklnk commented on boundingbox/__pycache__/BoundingBox.cpython-310.pyc
it's unnecessary

2023-11-10 21:27 UTC, vnmsklnk commented on decoding/.DS_Store
it's unnecessary

2023-11-10 21:27 UTC, vnmsklnk commented on decoding/__pycache__/decode.cpython-310.pyc
it's unnecessary

2023-11-10 21:27 UTC, vnmsklnk commented on decoding/decode.py
> +from abc import ABC, abstractmethod
let's sort imports alphabetically here and everywhere

2023-11-10 21:27 UTC, vnmsklnk commented on decoding/decode.py
> +        pass
It's better to just call it Decoder. The fact that it's an interface is obvious enough.

2023-11-10 21:27 UTC, vnmsklnk commented on decoding/decode.py
> +        pass
why `decode_p`? what `p` means?

2023-11-10 21:27 UTC, vnmsklnk commented on decoding/decode.py
> +        pass
why `input_img` is string? it should be `ndarray` (check your UML diagram)
also, there's only one `bounding_box` in your diagram

2023-11-10 21:27 UTC, vnmsklnk commented on decoding/decode.py
> +            print(decoded)
There should only be one class in a single file. So let's move this class

2023-11-10 21:27 UTC, vnmsklnk commented on localization/.DS_Store
all the unnecessary files should be removed

2023-11-10 21:27 UTC, vnmsklnk commented on localization/localize.py
> +
Same problems as with the decoder

2023-11-10 21:27 UTC, vnmsklnk commented on localization/localize.py
> +    def yolov7_method(input_img: str, detector_path: str):
The inheritor must implement the `localize` method

2023-11-10 21:27 UTC, vnmsklnk commented on localization/onnx_yolov7/__init__.py
We should avoid star imports

2023-11-10 21:27 UTC, vnmsklnk commented on main.py
> +# crop_helper(save_dir, input_img, bounding_boxes)
Let's do a little better formatting of the file. We need to remove the hardcoded paths and commented code

2023-11-10 21:27 UTC, vnmsklnk commented on requirements.txt
> +numpy
versions?

2023-11-10 21:27 UTC, vnmsklnk commented on utils.py
> +# def helper
what is it?

2023-11-14 22:56 UTC, vnmsklnk requested changes

2023-11-14 22:56 UTC, vnmsklnk commented on barcode_detection/PXL_20230826_081602262.jpg
I think it's better to create `example` folder in the root of the repo and move it there

2023-11-14 22:56 UTC, vnmsklnk commented on barcode_detection/boundingbox/BoundingBox.py
Let's rename file to `bounding_box.py`
https://stackoverflow.com/questions/42127593/should-python-class-filenames-also-be-camelcased

2023-11-14 22:56 UTC, vnmsklnk commented on barcode_detection/decoding/decode.py
> +import numpy as np
Let's divide imports into several types
1. `import ...`
2. `from ... import ...`
3. `from barcode_detection... import ...`
Every group is divided by line break and sorted alphabetically

2023-11-14 22:56 UTC, vnmsklnk commented on barcode_detection/decoding/decode.py
> +    def decode(self, input_img: np, bounding_boxes):
```suggestion
    def decode(self, input_img: np.ndarray, bounding_boxes: list[BoundingBox]):
```
`np` is not a type

2023-11-14 22:56 UTC, vnmsklnk commented on barcode_detection/decoding/decode_pyzbar.py
> +        for i in bounding_boxes:
```suggestion
        for box in bounding_boxes:
```

2023-11-14 22:56 UTC, vnmsklnk commented on barcode_detection/decoding/decode_pyzbar.py
> +            print(decoded)
My suggestion is not to print to the console, but to return a list of codes (None if the barcode is not recognized).

2023-11-14 22:56 UTC, vnmsklnk commented on barcode_detection/localization/localize.py
> +    def get_boundings(self, input_img: np):
```suggestion
    def get_boundings(self, input_img: np.ndarray) -> list[BoundingBox]:
```

2023-11-14 22:56 UTC, vnmsklnk commented on barcode_detection/main.py
Let's make a console script here, [as we've done before](https://github.com/prime-slam/place-recognition-db/blob/master/vprdb/converters/kitti_converter.py). For example, it can take a path to the weights and to an image (default value -- example photo from the repository). And this is where we can add printing to the console.

2023-11-14 22:56 UTC, vnmsklnk commented on barcode_detection/utils.py
> +        cv2.imwrite(filepath, cropped)
Seems like this is unused now

2023-11-15 21:23 UTC, vnmsklnk requested changes

2023-11-15 21:23 UTC, vnmsklnk commented on barcode_detection/decoding/decode.py
> +from barcode_detection.boundingbox.bounding_box import BoundingBox
These imports should be divided

2023-11-15 21:23 UTC, vnmsklnk commented on barcode_detection/decoding/decode_pyzbar.py
> +    def decode(self, input_img: np.ndarray, bounding_boxes):
```suggestion
    def decode(self, input_img: np.ndarray, bounding_boxes: list[BoundingBox]) -> list[list[str] | None]
```

2023-11-15 21:23 UTC, vnmsklnk commented on barcode_detection/localization/localize.py
> +from barcode_detection.boundingbox.bounding_box import BoundingBox
and here

2023-11-15 21:23 UTC, vnmsklnk commented on barcode_detection/localization/localize_yolo.py
> +    def get_boundings(self, input_img: np.ndarray):
```suggestion
    def get_boundings(self, input_img: np.ndarray) -> list[BoundingBox]:
```

2023-11-15 21:50 UTC, vnmsklnk approved these changes

2023-11-16 09:42 UTC, anastasiia-kornilova requested changes
Readme with instruction on how to install and run should be added

2023-11-16 09:42 UTC, anastasiia-kornilova commented on barcode_detection/boundingbox/bounding_box.py
> +        self.x = x
Not clear, what x, y describe -- center of BB? top left corner? At least some comments are required

2023-11-16 09:42 UTC, anastasiia-kornilova commented on barcode_detection/boundingbox/bounding_box.py
> +class BoundingBox:
I would rename `boundingbox` folder to smth more general, that refers to common data structures. Like `core` or `odm` (operational data model)

2023-11-16 09:42 UTC, anastasiia-kornilova commented on barcode_detection/boundingbox/bounding_box.py
> +        self.width = width
What for do you use width/height instead of corners, for example?

2023-11-16 09:42 UTC, anastasiia-kornilova commented on main.py
> +        raise Exception("not yet implemented")
`Not supported`, rather then `not yet`

2023-11-16 09:42 UTC, anastasiia-kornilova commented on main.py
> +        raise Exception("invalid localize option")
The same, use the common pattern for error messages

2023-12-16 17:30 UTC, merged